#include<iostream.h>
#include<conio.h>
#include<process.h>
int main(){
	int i;
	clrscr();
	cout<<endl<<"enter the number (for months)";
	cin>>i;
	if(i==1)
	{
	cout<<endl<<"january";
	}
	else if(i==2)
	{
	cout<<endl<<"february";
	}
	else if(i==3)
	{
	cout<<endl<<"march";
	}
	else if(i==4)
	{
	cout<<endl<<"april";
	}
	else if(i==5)
	{
	cout<<endl<<"may";
	}
	else if(i==6)
	{
	cout<<endl<<"june";
	}
	else if(i==7)
	{
	cout<<endl<<"july";
	}
	else if(i==8)
	{
	cout<<endl<<"august";
	}
	else if(i==9)
	{
	cout<<endl<<"september";
	}
	else if(i==10)
	{
	cout<<endl<<"october";
	}
	else if(i==11)
	{
	cout<<endl<<"november";
	}
	else
	{
	 cout<<"december";
	}
	getch();
	return 0;

}